### ISSUE TITLE
Fix defects at the output image

### ISSUE THREAD

**Issue by bitlater** [rtqichen/style-swap#19]
Hi, Ricky. Thank you for such amazing work! 
I learned decoder on MSCOCO and WikiArt datasets and tried to stylize a photo. I wonder if it is possible to fix some black and white spots at the stylized image. Examples:

With optimization process:
![brad_pitt_stylized_1 jpg-2](https://user-images.githubusercontent.com/15965145/27438694-c3b7b4f8-576e-11e7-89ea-4252502841fe.jpg)

With decoder, without optimization:
![brad_pitt_stylized_1 jpg-3](https://user-images.githubusercontent.com/15965145/27438703-c87290a8-576e-11e7-8ee0-5bd201ccb2cb.jpg)

Thank you for the answer!

**Comment by rtqichen** [comment]
Tbh I'm not sure there's a simple fix. The wikiart dataset is heavily biased towards those brownish colors, so the decoder just mostly produce brown colors.

 It may make more sense to use the neural-style loss instead of a reconstruction loss (at a single layer) to train the "decoder", which is what these guys did, https://arxiv.org/abs/1703.06868.
