### ISSUE TITLE
Speed slows down move than 100% if running on a machine with multi-gpu.

### ISSUE THREAD

**Issue by LambdaWill** [rtqichen/style-swap#30]
Sorry, I am wondering if you have encounter this problem and may give me some help...
I am faced with a very big performance problem in torch code and need help from you.
My code can only run on a single GPU.
When the I run my torch code on a machine which has single GPU, the speed is 0.5s per image. However,
when try running it on a machine which has multiple GPUs, it slows down to 1.2s per image.
More than 100% speed decrease！ I find that other gpus all have ~300Mb memory usages occpied by
the same thread. I think whether it is the bottleneck of the decrease. How to solve it? Big thanks!

**Comment by LambdaWill** [comment]
Update:
 'export CUDA_DEVICES_VISIBLE=5' makes no differences.
![1](https://user-images.githubusercontent.com/26055298/31814294-c3fcd4ba-b5bb-11e7-8c0c-77786430d181.png)

**Comment by rtqichen** [comment]
Sorry, when I did these experiments I only had a single GPU. I honestly didn't even know the code could be used with multiple GPUs. 
It's weird though because cost per iteration when doing optimization should only be a single pass through the first few layers of VGG. With the decoder, I might imagine that the overhead of having to load a very large convolutional layer could dominate.
